version: "3"
services:
  auth:
    build:
      context: ./
      dockerfile: apis/api_auth/Dockerfile
  ingredients:
    build:
      context: ./
      dockerfile: apis/api_ingredients/Dockerfile
  modeles:
    build:
      context: ./
      dockerfile: apis/api_modeles/Dockerfile
  procedes:
    build:
      context: ./
      dockerfile: apis/api_procedes/Dockerfile
  nginx:
    image: "nginx"
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
  app:
    build:
      context: ./
      dockerfile: src/Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
